# Generated by Django 5.2.1 on 2025-06-02 02:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_reciclaje', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudadano',
            options={'verbose_name': 'Ciudadano', 'verbose_name_plural': 'Ciudadanos'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['nombre'], 'verbose_name': 'Material', 'verbose_name_plural': 'Materiales'},
        ),
        migrations.AlterModelOptions(
            name='operario',
            options={'ordering': ['usuario__username'], 'verbose_name': 'Operario', 'verbose_name_plural': 'Operarios'},
        ),
        migrations.AlterModelOptions(
            name='solicitudretiro',
            options={'ordering': ['-fecha_solicitud'], 'permissions': [('can_assign_request', 'Puede asignar solicitudes a operarios')], 'verbose_name': 'Solicitud de retiro', 'verbose_name_plural': 'Solicitudes de retiro'},
        ),
        migrations.AddField(
            model_name='operario',
            name='capacidad_diaria',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacidad diaria de retiros'),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='direccion',
            field=models.CharField(max_length=200, verbose_name='Dirección completa'),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='telefono',
            field=models.CharField(max_length=15, verbose_name='Teléfono de contacto'),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='material',
            name='codigo',
            field=models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='material',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='material',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre del material'),
        ),
        migrations.AlterField(
            model_name='operario',
            name='fecha_contratacion',
            field=models.DateField(verbose_name='Fecha de contratación'),
        ),
        migrations.AlterField(
            model_name='operario',
            name='telefono',
            field=models.CharField(max_length=15, verbose_name='Teléfono de contacto'),
        ),
        migrations.AlterField(
            model_name='operario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='solicitudretiro',
            name='cantidad',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad estimada'),
        ),
        migrations.AlterField(
            model_name='solicitudretiro',
            name='ciudadano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_reciclaje.ciudadano', verbose_name='Ciudadano solicitante'),
        ),
        migrations.AlterField(
            model_name='solicitudretiro',
            name='comentarios',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='solicitudretiro',
            name='estado',
            field=models.CharField(choices=[('PEN', 'Pendiente'), ('RUT', 'En ruta'), ('COM', 'Completada'), ('CAN', 'Cancelada')], default='PEN', max_length=3, verbose_name='Estado actual'),
        ),
        migrations.AlterField(
            model_name='solicitudretiro',
            name='fecha_estimada',
            field=models.DateField(verbose_name='Fecha estimada de retiro'),
        ),
        migrations.AlterField(
            model_name='solicitudretiro',
            name='fecha_solicitud',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud'),
        ),
        migrations.AlterField(
            model_name='solicitudretiro',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_reciclaje.material', verbose_name='Material a retirar'),
        ),
        migrations.AlterField(
            model_name='solicitudretiro',
            name='operario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_reciclaje.operario', verbose_name='Operario asignado'),
        ),
    ]
